"""empty message

Revision ID: 58859d8dd469
Revises: cbedaae8e5b4
Create Date: 2017-12-26 15:19:31.418444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58859d8dd469'
down_revision = 'cbedaae8e5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
