"""initial migration

Revision ID: 786e8046f3a0
Revises: 860c4dde6afe
Create Date: 2017-12-20 19:28:30.176019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786e8046f3a0'
down_revision = '860c4dde6afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
